server_uri: bolt://151.106.35.64:7687
admin_user: neo4j
admin_pass: l5IKrx07DGYdclK

mod: async
thread_count: 4

files:
  - url: /home/cuneyttyler/knowledgebase/dbpedia/infobox-properties_lang=en.ttl.bz2
    type: ttl
    compression: bz2
    chunk_size: 1000
    skip_chunks: 0
    cql: |
         WITH $dict.rows AS rows UNWIND rows as row
           MATCH(subject:Entity) where subject.dbpedia_uri = row.subject
           WITH *, 'number' as numberStr, 'time' as timeStr, 'string' as stringStr, 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type' as typeUriStr, 'Type' as typeNameStr
              WITH *, row.object as object_ WHERE NOT object_ CONTAINS 'http://dbpedia.org'
                  WITH *, row.type as type_ WHERE type_ is not null and type_ = "http://www.w3.org/2001/XMLSchema#date"
                    CREATE(object:Property {value: row.object, type: timeStr, datatype: timeStr})
                          WITH * CALL apoc.create.relationship(object, typeUriStr ,{name: typeNameStr},mp) YIELD rel
                        WITH * CALL apoc.create.relationship(subject,row.predicate,{name: apoc.text.capitalize(replace(row.predicate,"http://dbpedia.org/property/","")), source: "dbpedia", type: "literal"}, object.object) YIELD rel RETURN null



