server_uri: bolt://localhost:7687
admin_user: neo4j
admin_pass: 94BuJ2\h7i1+

mod: async
thread_count: 8

files:
  - url: D:/Dev/Dbpedia/instance-types_lang=en_specific.ttl.bz2
    compression: bz2
    type: ttl
    chunk_size: 100
    cql: |
      WITH $dict.rows AS rows UNWIND rows as row
        MERGE(e:Entity {dbpedia_uri: row.subject})
        MERGE(e2:Entity {dbpedia_uri: row.object})
        CREATE(e)-[rel:INSTANCE_OF {source:'dbpedia', uri: row.predicate}]->(e2)
