server_uri: bolt://localhost:7687
admin_user: neo4j
admin_pass: 94BuJ2\h7i1+

mod: async
thread_count: 8

files:
  - url: D:/Dev/Dbpedia/long-abstracts_lang=en.ttl.bz2
    compression: bz2
    type: ttl
    chunk_size: 100
    cql: |
      WITH $dict.rows as rows UNWIND rows as row
        MERGE(subject:Entity {dbpedia_uri: row.subject})
        SET subject.description=row.object
