server_uri: bolt://localhost:7687
admin_user: neo4j
admin_pass: 94BuJ2\h7i1+

mod: async
thread_count: 8

files:
  - url: D:/Dev/Dbpedia/ontology--DEV_type=parsed.nt
    compression: none
    type: ttl
    chunk_size: 100
    cql: |
      WITH $dict.rows AS rows UNWIND rows as row
        MERGE(e:Entity {dbpedia_uri: row.subject, name: replace(replace(row.subject,'http://dbpedia.org/ontology/',''),'_',' ')})
        WITH * where row.predicate = 'http://www.w3.org/2000/01/rdf-schema#subClassOf' or row.predicate = 'http://www.w3.org/2000/01/rdf-schema#domain'
          MERGE(e2:Entity {dbpedia_uri: row.object, name: replace(replace(row.object,'http://dbpedia.org/ontology/',''),'_',' ')})
          WITH * CREATE(e)-[rel:SUBCLASS_OF {uri:row.predicate, source: 'dbpedia'}]->(e2)
