server_uri: bolt://localhost:7687
admin_user: neo4j
admin_pass: 94BuJ2\h7i1+

mod: async
thread_count: 8
pre_ingest:
  - MERGE(property:MetaProperty {uri:'http://www.w3.org/1999/02/22-rdf-syntax-ns#Property', name:'Property'})

files:
  - url: D:/Dev/Dbpedia/infobox-property-definitions_lang=en.ttl.bz2
    type: ttl
    compression: bz2
    chunk_size: 100
    skip_chunks: 0
    cql: |
      MATCH(property:MetaProperty) where property.name = 'Property'
      WITH property, $dict.rows AS rows UNWIND rows as row
        WITH row, property, row.predicate as predicate where predicate = 'http://www.w3.org/2000/01/rdf-schema#label'
        CREATE(metaProperty:MetaProperty {uri: row.subject, name: apoc.text.capitalize(row.object), source: 'dbpedia'})
        WITH * CREATE(metaProperty)-[rel:TYPE_OF {uri:'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'}]->(property)


