server_uri: bolt://localhost:7687
admin_user: neo4j
admin_pass: cuneyt123
mod: async
thread_count: 2

files:
  - url: /home/cnytync/Dev/dbpedia/sameAs_lang=en.ttl.bz2
    compression: bz2
    type: ttl
    chunk_size: 100
    skip_records: 9100
    cql: |
      WITH $dict.rows AS rows UNWIND rows as row
        WITH row WHERE  row.object CONTAINS "wikidata"
        MERGE(e:Entity {wikidataId: replace(row.object,"http://www.wikidata.org/entity/","")})
        SET e.dbpedia_uri = row.subject, e.entity_type = "semantic_web", e.cr_date = datetime()


