server_uri: bolt://localhost:7687
admin_user: neo4j
admin_pass: cuneyt123

mod: async
thread_count: 8

files:
  - url: PATH_TO_FILE
    compression: zip
    type: json
    chunk_size: 100
    cql: |
