server_uri: bolt://localhost:7687
admin_user: neo4j
admin_pass: cuneyt123

mod: async
thread_count: 8

files:
  - url: /media/drived/dbpedia/sameAs_lang=en.ttl.bz2
    compression: bz2
    type: ttl
    chunk_size:  500
    cql: |
      WITH $dict.rows AS rows UNWIND rows as row
        MERGE(e:Entity {dbpedia_uri: row.subject})
        SET e.wikidata_id = replace(row.object,"http://www.wikidata.org/entity/",""), e.entity_type= 'semantic_web', e.cr_date= datetime()
