server_uri: bolt://151.106.35.64:7687
admin_user: neo4j
admin_pass: l5IKrx07DGYdclK

mod: async
thread_count: 64

files:
  - url: /home/cuneyttyler/knowledgebase/dbpedia/long-abstracts_lang=fr_uris=en.ttl.bz2
    compression: bz2
    type: ttl
    chunk_size: 500
    cql: |
      WITH $dict.rows as rows UNWIND rows as row
        MERGE(subject:Entity {dbpedia_uri: row.subject})
        SET subject.description=row.object
